### ISSUE TITLE
Issue while configuring vcf integration with VMware Aria Operations due to certificate

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#535]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.9.0.1029

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while configuring vcf integration with VMware Aria Operations

Error at script line 18629

Relevant Command: $adapterDetail.'adapter-certificates' = $adapterDetail.'adapter-certificates' | Select-Object * -ExcludeProperty certificateDetails

### Error or Debug Output

'''Powershell
[03-13-2024_08:13:28] [...] INFO Attempting to Configure the VMware Cloud Foundation Integration with VMware Aria Operations
[03-13-2024_08:13:31] [...] INFO  Error at Script Line 18629  Relevant Command: if ($adapterDetail.ContainsKey('adapter-certificates')) {  Error Message: You cannot call a method on a null-valued expression.
[03-13-2024_08:13:31] [...] ERROR System.Management.Automation.CmdletInvocationException: {"message":"Invalid request... #1 violations found.","validationFailures":[{"failureMessage":"Adapter and credential should refer to the same adapter type.","violationPath":"credential"}],"httpStatusCode":400,"apiErrorCode":400}
 ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (400).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) {"message":"Invalid request... #1 violations found.","validationFailures":[{"failureMessage":"Adapter and credential should refer to the same adapter type.","violationPath":"credential"}],"httpStatusCode":400,"apiErrorCode":400} {"message":"Invalid request... #1 violations found.","validationFailures":[{"failureMessage":"Adapter and credential should refer to the same adapter type.","violationPath":"credential"}],"httpStatusCode":400,"apiErrorCode":400} Response status code does not indicate success: 400 (400). You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression. You cannot call a method on a null-valued expression.
'''

### Expected Behavior

The adapter should be configured successfully

### Actual Behavior

The adapter is unable to find the nsx certificate generated.

### Steps to Reproduce

Invoke-IOM deployment when triggered fails at step configuring vcf integration with VMware Aria Operations

**Comment by GaryJBlake** [comment]
Hitting the issue again, there seems to be a failure when verifying the adapter. If you retry it progresses.

**Comment by GaryJBlake** [comment]
Performed further investigation, the issue is due to the incorrect service account being assign a Global Permission in vCenter Server and then when we try to configure and validate the connection to vCenter Server it does not have the correct access.
