### ISSUE TITLE
ILA: Issue while installing Workspace ONE Access Content Pack

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#583]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.10.0.1011

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while running Invoke-ILAdeployment at step Install Workspace ONE Access Content Pack

### Error or Debug Output

```powershell
[04-18-2024_09:57:04] [INFO] Install Workspace ONE Access Content Pack
 [04-18-2024_09:57:05] [INFO]  Error at Script Line 15766
 [04-18-2024_09:57:05] [INFO]  Relevant Command: $response = Invoke-RestMethod -Method 'GET' -Uri $Uri -Headers $ghHeaders
 [04-18-2024_09:57:05] [INFO]  Error Message: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
 [04-18-2024_09:57:05] [ERROR] Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."
 [04-18-2024_09:57:05] [ERROR] System.Management.Automation.CmdletInvocationException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
 ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 [04-18-2024_09:57:05] [ERROR] {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
 [04-18-2024_09:57:05] [ERROR] System.Management.Automation.CmdletInvocationException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
 ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 [04-18-2024_09:57:05] [ERROR] {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
 [04-18-2024_09:57:05] [ERROR] Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
 [04-18-2024_09:57:05] [ERROR] Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
 [04-18-2024_09:57:05] [ERROR] Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

### Expected Behavior

There should not any errors while running Invoke-ILAdeployment

### Actual Behavior

Error while installing Workspace ONE Access Content Pack

### Steps to Reproduce

Run Invoke-ILAdeployment and it will fail at step Install Workspace ONE Access Content Pac

**Comment by GaryJBlake** [comment]
**Issue 1** - Your API Token does not have access to the Git Hub Repository, adding some code to check the initial response from the API to retrieve the Content Pack index

**Comment by GaryJBlake** [comment]
Identified a number of additional errors whilst triaging the issue further:

- Sometimes can't get the content pack URL
- Sometimes hitting 403 (rate limit exceeded)
- Sometimes not being able to get the initial content pack list

I've enhanced the function to handle the above use cases, however the workflow is still not consistent when executed so further investigation is needed.

**Comment by GaryJBlake** [comment]
Reassigned to @tenthirtyam to further investigate

**Comment by tenthirtyam** [comment]
I'm on it.
