### ISSUE TITLE
Add-SrmLicenseKey is failing with Could not find any of the servers specified by name

### ISSUE THREAD

**Issue by GaryJBlake** [vmware/power-validated-solutions-for-cloud-foundation#600]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1.1

### Module Version

2.10.0.1026

### PowerShell Version

7.4.2

### PowerCLI Version

13.2.1.22851661

### PowerVCF Version

2.4.1.1000

### Guest Operating System

Windows Server 2022

### Environment Details

Standard nested internal lab

### Description

When executing the `Add-SrmLicenseKey` cmdlet it sometimes errors

### Error or Debug Output

```powershell
[05-03-2024_12:12:31] [INFO] Assigning Licenses to Site Recovery Manager for Site Protection and Disaster Recovery for VMware Cloud Foundation
[05-03-2024_12:12:36] [INFO]  Error at Script Line 6940
[05-03-2024_12:12:36] [INFO]  Relevant Command: Disconnect-SrmServer -Server $srmFqdn -Force -Confirm:$false
[05-03-2024_12:12:36] [INFO]  Error Message: 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] Unable to connect to the remote server: dr.fault.SessionLimitExceeded
[05-03-2024_12:12:36] [ERROR] Unable to connect to the remote server: dr.fault.SessionLimitExceeded
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find SrmServer with name 'sfo-m01-srm01.sfo.rainpole.io'.	
[05-03-2024_12:12:36] [ERROR] System.Management.Automation.CmdletInvocationException: 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
 ---> VMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.ServerObnFailureException: 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ObnSelector.TerminateObnProcessingDueToServerObnFailure(String errorId, ErrorCategory errorCategory, Object targetObject, Exception innerException, String connectionId, Object[] messageParams)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ObnSelector.SetParameterNewValue(PropertyInfo parameter, ArrayList expandedItemList)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ObnSelector.SelectObjectByName(PropertyInfo parameter)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ObnSelector.SelectServerByName()
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.SelectServerByName()
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.ProcessRecordErrorHandled()
   at VMware.VimAutomation.Srm.Commands.Commands.BaseSrmCmdlet.ProcessRecordErrorHandled()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
[05-03-2024_12:12:36] [ERROR] 5/3/2024 12:12:36	Disconnect-SrmServer		Could not find any of the servers specified by name.	
```

### Expected Behavior

Adding a license should complete without any issue or report a single POST_VALIDATION_FAILURE

### Actual Behavior

Failed

### Steps to Reproduce

Execute `Add-SrmLicenseKey` on the command line

**Comment by GaryJBlake** [comment]
### Investigation 

#### Issue 1:

When the function authenticates to SRM its failing but no error is return to the user

#### Issue 2:

Disconnecting from the SRM server is failing due to the placement of the disconnect within the function.

#### Issue 3

Found that the Undo-SrmLicenseKey cmdlet is not even disconnecting from the SRM server
